-keep class net.schmizz.sshj.** { *; }
-keep class net.i2p.crypto.eddsa.** { *; }
-dontwarn com.google.errorprone.annotations.**
-dontwarn sun.security.x509.**
-dontwarn net.schmizz.sshj.**
-dontwarn net.i2p.crypto.eddsa.**
